### ISSUE TITLE
cant drop items

### ISSUE THREAD

**Issue by DoktorHolzbein** [nekiro/TFS-1.4-Downgrades#1]
it seems like you cannot drop any items
does not matter if you are player or gm

tested it on account with acc type 5
and on a normal account aswell

**Comment by nekiro** [comment]
The issue appears to be with EventCallbacks.
https://github.com/nekiro/TFS-1.4-Downgrades/blob/8.60/data/events/scripts/player.lua#L42

**Comment by nekiro** [comment]
Fixed in https://github.com/nekiro/TFS-1.4-Downgrades/commit/2a6975cd25de21d2c73f0d2423a1bd2b026e220b

**Comment by nekiro** [comment]
Next time, respect the issue template please.
