### ISSUE TITLE
Missing house information when looking at some house doors

### ISSUE THREAD

**Issue by Znote** [nekiro/TFS-1.4-Downgrades#15]
**Protocol version**
8.60

**Describe the bug**
When looking at the door of this house, there is no description to who own the house, or what name the house has. 
But even when you are not the owner of the house, you can still open and close it. 

**To Reproduce**
1. Go to the first house south for Rhyves depot.
2. Click on the door to toggle open/close state, even if you are not the owner. 
3. Look on the door and see no house information. 

**Expected behavior**
If I am not the owner/gm, I should not be able to open or close the door.
If I look at the door, I should be able to see the name of the house and who owns it.

**Screenshots**
![image](https://user-images.githubusercontent.com/1552144/117694205-25718a80-b1bf-11eb-93b3-dcfc151af7e8.png)
![image](https://user-images.githubusercontent.com/1552144/117694249-36220080-b1bf-11eb-88d2-c476bfb45fb1.png)

**Additional context**
Looks to be semi related to: https://github.com/nekiro/TFS-1.4-Downgrades/issues/14
Appears the door system is out of whack.

**Comment by Znote** [comment]
![image](https://user-images.githubusercontent.com/1552144/117696985-3ec80600-b1c2-11eb-9d95-85fb6833bb33.png)
![image](https://user-images.githubusercontent.com/1552144/117697017-49829b00-b1c2-11eb-94a6-177e5b1b94cc.png)
![image](https://user-images.githubusercontent.com/1552144/117697216-82227480-b1c2-11eb-8031-8188029a36b2.png)
![image](https://user-images.githubusercontent.com/1552144/117697243-89e21900-b1c2-11eb-80dd-a81232f31896.png)

House looks to be correctly configured in the map. 

https://github.com/nekiro/TFS-1.4-Downgrades/blob/8.60/data/world/forgotten-house.xml
House looks to be correctly configured in the xml file.

**Comment by Znote** [comment]
South house: Door id 0
![image](https://user-images.githubusercontent.com/1552144/117699912-a764b200-b1c5-11eb-9e05-50e71c9493fa.png)

East house: Door id 1
![image](https://user-images.githubusercontent.com/1552144/117699972-bea39f80-b1c5-11eb-807c-690ecace0acb.png)

Gonna try to swap ids to see if that correlates to the issue.

**Comment by EPuncker** [comment]
> So the map is at fault for both this and #14?

yep

**Comment by Znote** [comment]
@EPuncker Since you are familiar with [map conversions](https://github.com/nekiro/TFS-1.4-Downgrades/pull/10), perhaps you could patch up a PR? :)
