### ISSUE TITLE
Summon received exp

### ISSUE THREAD

**Issue by EPuncker** [nekiro/TFS-1.4-Downgrades#27]
**Protocol version**
8.60

**Describe the bug**
The received experience points from the summon that should appear over his head are not showing

**To Reproduce**
1. Utevo res any monster
2. Kill something else with it
3. See error

**Comment by nekiro** [comment]
Fixed in https://github.com/nekiro/TFS-1.4-Downgrades/commit/7deea36b6e0978cd2616804ede9c285a72542bed
