### ISSUE TITLE
Throwing items

### ISSUE THREAD

**Issue by AK94PL** [nekiro/TFS-1.4-Downgrades#36]
> 
> 
> was a long time since i played around with these ot files, but i just discovered that the throwing distance doesn't seem to be that accurate, here is a comparison:
> 
> ![123](https://user-images.githubusercontent.com/43324808/70586344-13a14780-1bc7-11ea-99a0-232bce7ef591.PNG)
> 
> is any1 still working with these files fixing stuff? : )

Hello, I got that same problem (like in linked issue in Nostalriusm) in your distribution. Exist any solution ?

https://github.com/TwistedScorpio/Nostalrius/issues/55

**Comment by emil92b** [comment]
can confirm this issue exists on both nostalrius and this downgrade, also not a upstream bug

**Comment by nekiro** [comment]
I would say its, because dat file attributes differs from 1098 tibia, so sight line works for 1098, but not for this version.

**Comment by AK94PL** [comment]
> 
> 
> I would say its, because dat file attributes differs from 1098 tibia to 8.60, so sight line (its 1:1 to master tfs 1098) works for 1098, but not for this version.

Any idea how to fix it ?

**Comment by ForgottenOldschool** [comment]
why would this be a bug? if there nothing boking sight why item should be not droppable in that place for the roof?

**Comment by dami1310** [comment]
It's not about a distance, roof border is blocking it.

**Comment by nekiro** [comment]
@AK94PL you can revisit this problem now, because latest sight line changes were merged from upstream. If it does not change the behaviour you have to get rid of "block projectile" flag on this item that is blocking the throw.
