### ISSUE TITLE
Onlook is not working // on use  is not working either

### ISSUE THREAD

**Issue by ForgottenOldschool** [nekiro/TFS-1.4-Downgrades#39]
If i click anywhere or on any item the description is not being displayed. can't at look players, items or anything, this occurs in tfs 772 too 1.4. clean datapack

**Comment by ForgottenOldschool** [comment]
also can't use anything or eat

**Comment by nekiro** [comment]
Use issue template.

**Comment by nekiro** [comment]
Probably invalid, keep in mind that this downgrade is 100% compatible with **cip clients**. If you use otcv8 make sure your problem is also happening on regular cip client, closing this for now.

**Comment by Znote** [comment]
I think onlook is related to data pack, make sure the onlook message id is compatible with your client. 
I remember fixing some ids in the default data pack, etc party loot or something that doesn't work in 8.6. I just had to change the message id to green description and it worked. 

There is nothing wrong with the source code
![image](https://user-images.githubusercontent.com/1552144/127252082-bb135516-c9cc-4e76-bfac-662307c3c393.png)

Although it might be a good idea to alias high-protocol message types to downprotocol candidate.
