### ISSUE TITLE
Repo tips and suggestions

### ISSUE THREAD

**Issue by Znote** [nekiro/TFS-1.4-Downgrades#4]
**Readme file:**
Add commit hash of otland/forgottenserver in readme file so we know where the fork occured. This will make it easier for git freaks like me to add otland/forgottenserver as a remote and cherry pick stuff. 

**Enable wiki:**
You dont need to use it, but I might add a few findings and useful tips there as I go along. I might add a page that helps people convert TFS 0.3.6 servers to this TFS 1.4 downport etc... 

**Issue labels:**
Tag issues with labels: bug, suggestion, feature, enhancement etc. 
Labels for closed issues: solved, irrelevant, rejected, unrelated

If you find it bothersome to maintain, add me as a collaborator in the repo settings, I can help you out. :)

**Comment by nekiro** [comment]
Yeah. I invited you :D
