### ISSUE TITLE
Doors not working in 7.72

### ISSUE THREAD

**Issue by dnvd** [nekiro/TFS-1.4-Downgrades#42]
**Protocol version**
7.72

**Describe the bug**
Cannot open/close doors. (Seems to be using global door variables that hasn't been set.)

**To Reproduce**
1. Login to server
2. Try to open/close a normal closed door

Haven't tried all door types. Might be the same issue for all of them.

**Expected behavior**
Door should open/close

**Comment by nekiro** [comment]
Can you give me example door ids?

**Comment by dnvd** [comment]
1213

**Comment by dnvd** [comment]
The problem seems to be in data/actions/scripts/other/doors.lua where global variables are used that doesn't exists

**Comment by nekiro** [comment]
Should be fixed with recent commits, close and confirm if so

**Comment by dnvd** [comment]
Seems to work, thank you for fixing this so quickly :)
