### ISSUE TITLE
NPCs not responding in 7.72

### ISSUE THREAD

**Issue by dnvd** [nekiro/TFS-1.4-Downgrades#43]
**Protocol version**
7.72

**Describe the bug**
Example NPCs not responding to greetings

**To Reproduce**
1. Go to the oracle
2. Type "hi"

**Expected behavior**
Expected greeting callback

**Additional info**
Tried looking at some other NPC files which included the greeting.lua file.
Adding this crashes the client when greeting the npc unfortunately.

**Comment by nekiro** [comment]
Fixed in https://github.com/nekiro/TFS-1.4-Downgrades/commit/ca60608bd59e326b2a24d7df4076d2caaa59d952
