### ISSUE TITLE
Explosion rune crashes client 7.72

### ISSUE THREAD

**Issue by dnvd** [nekiro/TFS-1.4-Downgrades#44]
**Protocol version**
7.72

**Describe the bug**
Shooting explosion rune crashes client "sometimes". (Very high chance for me)

**To Reproduce**
Shoot explosion rune

**Expected behavior**
Explosion should appear on target

**Comment by nekiro** [comment]
Most likely just effect problem, fix the effect in explosion rune lua file in spells directory.

**Comment by dnvd** [comment]
Yeah, you are right. I'll make a PR
