### ISSUE TITLE
Runes/Potions aren't stacking

### ISSUE THREAD

**Issue by Uore** [nekiro/TFS-1.4-Downgrades#50]
**Protocol version**
In protocol 8.00

**Describe the bug**
Runes and the potions aren't stacking if you have more than one from the same type.

**To Reproduce**
1. Create stackable items like fireball rune with this id 2302.
2. Create more than one.
3. It will be treated as a regular item and it takes space in the backpack.
4. No errors.

**Expected behavior**
It should be to stack.

**Screenshots**

https://user-images.githubusercontent.com/69870068/128167611-46b9adfc-8bd5-4bd5-836a-9728db6cca2a.mp4

**Additional context**
There's no such more info.

**Comment by nekiro** [comment]
I don't think runes on 8.0 protocol stacked, runes on this protocol got special charges.
