### ISSUE TITLE
Npc |TRAVELCOST| not working?

### ISSUE THREAD

**Issue by dnvd** [nekiro/TFS-1.4-Downgrades#52]
**Protocol version**
7.72

**Describe the bug**
I'm really unsure if this is a problem on my side or the project. That said, delete this if I'm wrong (still trying to learn the setup of this project).
I've added a few captain npcs and I'm getting a problem where |TRAVELCOST| is written out in clear text instead of the actual travel cost which has been added to one of the files.

**To Reproduce**
1. Create a npc using the |TRAVELCOST| keyword
2. Say hi => (destination)
3. The npc answers with |TRAVELCOST| as a text instead of the actual number

**Expected behavior**
Expected travel cost to be printed out

Do I need any additional setup for this to work?

This is the captain I'm testing:
https://github.com/peonso/tibialegacyserver/blob/master/server/data/npc/scripts/Captain%20Bluebear.lua

**Comment by nekiro** [comment]
Might be related to change from npc channel to raw "say" message

**Comment by dnvd** [comment]
Ah yes you are right, I was looking at my modified files. You can delete this.

**Comment by nekiro** [comment]
Yeah, upstream tfs does not have this kind of functionality at all.
