### ISSUE TITLE
Parcel system in 7.72

### ISSUE THREAD

**Issue by dnvd** [nekiro/TFS-1.4-Downgrades#53]
**Protocol version**
7.72

**Describe the bug**
Parcels disappears after save & restart.

**To Reproduce**
1. Send a parcel to yourself
2. Save & exit server
3. Start the server again and the parcel won't be there

See screenshot for error message. (I think this started to appear after sending the first parcel).

**Expected behavior**
Expected parcels to be saved

**Screenshots**
![image](https://user-images.githubusercontent.com/88395501/128384850-09754393-c889-4704-b00b-a687e568d43a.png)

**Comment by nekiro** [comment]
Fixed in https://github.com/nekiro/TFS-1.4-Downgrades/commit/f90732099a6623df967faf55e0d5211b5855f706
