### ISSUE TITLE
Suggestion adding old attributes

### ISSUE THREAD

**Issue by zydent** [nekiro/TFS-1.4-Downgrades#57]
**Protocol version**
I think it will be good in all protocols to support these attributes.

**Describe the bug**
Missing old attributes like.

```
increasemeleevalue
increasemeleepercent
 
increasemagicvalue
increasemagicpercent
 
increasehealingvalue
increasehealingpercent
```

**Comment by nekiro** [comment]
You can try using this or wait for it to be completed.
https://github.com/otland/forgottenserver/pull/2807
Other than that. I won't work on this feature as it's not by anyhow connected to the protocol downgrades.
