### ISSUE TITLE
Not working NPC Eryn TFS 1.4 7.72

### ISSUE THREAD

**Issue by CatDealers** [nekiro/TFS-1.4-Downgrades#58]
**Protocol version**
7.72

**Screenshots**
https://prnt.sc/1npw7p4
https://prnt.sc/1npxjhv
![image](https://user-images.githubusercontent.com/87492533/129294085-48ab7f68-6e15-47af-b3cd-eb55911a26be.png)

**Additional context**

npc Eryn is not working

**Comment by nekiro** [comment]
Not an engine error, but npc files problem. Fix the npc lua file item ids.
