### ISSUE TITLE
[FIXED] ERROR COMPILING UBUNTU 20.04 [8.60 VERSION]

### ISSUE THREAD

**Issue by CatDealers** [nekiro/TFS-1.4-Downgrades#60]
**Protocol version**
8.60 | Source Lastet

**Screenshots**
https://prnt.sc/1r9nac9
![image](https://user-images.githubusercontent.com/87492533/132114612-cb5db5ca-b84d-4d8a-a5cc-466337d5e913.png)

**Comment by CatDealers** [comment]
![image](https://user-images.githubusercontent.com/87492533/132116495-774e32fb-dbbf-4ec3-bb9c-b26d30be3a33.png)

Go to enums.h file path

find function by code

```
	REPORT_REASON_SERVICEAGREEMENT = 20
};
```
Add

Add code below
```
enum BugReportType_t : uint8_t {
	BUG_CATEGORY_MAP = 0,
	BUG_CATEGORY_TYPO = 1,
	BUG_CATEGORY_TECHNICAL = 2,
	BUG_CATEGORY_OTHER = 3
};
```
So image
![image](https://user-images.githubusercontent.com/87492533/132116532-68e0742c-e287-4d62-81b7-22c8dda6c391.png)

It's working, I was tested and it worked. no errors and debug decided to close

**Comment by nekiro** [comment]
Care to open pr?

**Comment by CatDealers** [comment]
what pr ?

Em Dom, 5 de set de 2021 07:46, nekiro ***@***.***> escreveu:
