### ISSUE TITLE
Magic walls & almost all walls

### ISSUE THREAD

**Issue by Lording23** [nekiro/TFS-1.4-Downgrades#61]
https://user-images.githubusercontent.com/53460029/133885658-76e6d14e-9541-4181-b1a7-e11a4091398a.mp4

I dont know from where to start to check it out, anyone knows ?

**Comment by Lording23** [comment]
This is NOT a gm account, and sometimes it doesn't let you mwall at all even if it's supposed to be possible.

**Comment by nekiro** [comment]
Use issue template, it's there for a reason.

**Comment by Erza** [comment]
This is probably going to be fixed after nekiro syncs with the upstream

**Comment by Lording23** [comment]
> Use issue template, it's there for a reason.

My bad. 

This is a bug in the software that resides in this repository, and not a support matter
This issue is reproducible without changes to the code in this repository

How to reproduce:
It's random, sometimes it throw all walls(or items, anything. I will talk about mwalls this time) even if it isn't supposed to be possible. EXAMPLE:

https://user-images.githubusercontent.com/53460029/134056997-d1f2d158-c413-492c-a0c0-d775931541e6.mp4


And if you pick a new line to keep shooting magic walls it could not even shoot a simple one. EXAMPLE:

https://user-images.githubusercontent.com/53460029/134057132-3737c5e9-f7f1-411d-bb64-d9033c42b671.mp4

Also there's an image if you are goin to test what's possible or not.

![imagensz](https://user-images.githubusercontent.com/53460029/134057279-e5926835-9d65-4a04-87d3-d2a088f8d6d7.png)

I tried to play with this function in actions.cpp and looks like checkLineOfSight it's the right one, but I couldn't manage to fix it:

`ReturnValue Actions::canUseFar(const Creature* creature, const Position& toPos, bool checkLineOfSight, bool checkFloor)
{
	if (toPos.x == 0xFFFF) {
		return RETURNVALUE_NOERROR;
	}

	const Position& creaturePos = creature->getPosition();
	if (checkFloor && creaturePos.z != toPos.z) {
		return creaturePos.z > toPos.z ? RETURNVALUE_FIRSTGOUPSTAIRS : RETURNVALUE_FIRSTGODOWNSTAIRS;
	}

	if (!Position::areInRange<7, 5>(toPos, creaturePos)) {
		return RETURNVALUE_TOOFARAWAY;
	}

	if (checkLineOfSight && !g_game.canThrowObjectTo(creaturePos, toPos, checkLineOfSight, checkFloor)) {
		return RETURNVALUE_CANNOTTHROW;
	}

	return RETURNVALUE_NOERROR;
}`

**Comment by Zbizu** [comment]
I've reproduced situation from your screenshot. Neither of these tiles can be reached from this angle (sightline is same for both throwing items and spells)
![obraz](https://user-images.githubusercontent.com/5205079/134751388-d75df127-3ae8-4402-9d70-297d886df99b.png)

**Comment by Lording23** [comment]
Both should be reachable but if 1 magic wall reach the one of the left then the next one shouldn't be reachable. Acording to 7.x 8.x and im sure 9.x I dont know if tibia 12 doesn't works like this but indeed this was how tibia works. Video:


https://user-images.githubusercontent.com/53460029/134753887-a2dae2a5-7479-4a90-91b9-b33261e75acc.mp4

**Comment by nekiro** [comment]
That downgrade you linked used the old TFS sight line code, which is not 1:1 to cip sight line code. Downgrade uses the new sight line code, thus the differences. Anyway I wont consider this a bug, but "protocol feature".

**Comment by nekiro** [comment]
Downgrades were synced with upstream, so if there is "bug", it's likely protocol difference, which I'm not going to fix.
