### ISSUE TITLE
stairJumpExhaustion

### ISSUE THREAD

**Issue by 3Magic** [nekiro/TFS-1.4-Downgrades#62]
**Protocol version**
8.60

**Describe the bug**
Changing the value in stairJumpExhaustion doesn't change in game.

**To Reproduce**
1. Go to config.lua
2. Change stairJumpExhaustion to 0
3. Reload config

**Expected behavior**
stairJumpExhaustion should change... well... the stair jump exhaustion

**Screenshots**
N/A

**Additional context**
N/A

**Comment by nekiro** [comment]
Code for stairJumpExhaustion is 1:1 to upstream code. If it doesn't work, then it doesn't work on upstream too.

**Comment by Emilianenko** [comment]
stairJumpExhaustion occurs when you go up or down a stair, and try to use some agressive spell or rune.The exhaustion is for the agressive spells and runes, not for the stair jump itself.
