### ISSUE TITLE
Make string config with integer ip

### ISSUE THREAD

**Issue by ramon-bernardo** [nekiro/TFS-1.4-Downgrades#67]
**Protocol version**
7.72/8.00/8.60

**Describe the bug**
````
if (string[IP] == "") {
    string[IP] = getGlobalString(L, "ip", "127.0.0.1");
}
````

**To Reproduce**
1 - Run with debug x64 = excep error
but work with release

**Additional context**
- change to IP_STRING

**Comment by nekiro** [comment]
Yeah, I probably forgot to change this one, thanks!

**Comment by nekiro** [comment]
Fixed in https://github.com/nekiro/TFS-1.4-Downgrades/commit/41dd7826af1b3d75a5ab028d51f7e60a107748f4
