### ISSUE TITLE
Blank Rune Bug

### ISSUE THREAD

**Issue by paola92** [nekiro/TFS-1.4-Downgrades#69]
**Protocol version**
8.00

**Describe the bug**
If blank rune is in backpack/bag and we close this we cannot open it on OTClient or default client will crash.

**To Reproduce**
1. Buy blank rune from NPC (it will not take money).  It's also possible by create /i blank rune.
2. Close backpack
3. Try open

**Expected behavior**
Should work normally

**Screenshots**
Simple to reproduce

**Additional context**
Nothing to add

**Comment by paola92** [comment]
I think it can be caused by this that blank rune is not stacking.

**Comment by nekiro** [comment]
Fixed in https://github.com/nekiro/TFS-1.4-Downgrades/commit/d85f0d94cd44654c3a0628504397a104c742290c
