### ISSUE TITLE
Ctrl+z to report bug kick player also during fight

### ISSUE THREAD

**Issue by paola92** [nekiro/TFS-1.4-Downgrades#70]
**Protocol version**
8.00

**Describe the bug**
when we click ctrl+z nad report bug and click OK, player is kicked from server

**To Reproduce**
1. ctrl+z
2. wrtie something
3. click ok

**Expected behavior**
should just send report

**Screenshots**
simple to reproduce

**Additional context**
simple to reproduce

**Comment by gesior** [comment]
In **protocolgame.cpp** replace:
```
void ProtocolGame::parseBugReport(NetworkMessage& msg)
{
	uint8_t category = msg.getByte();
	std::string message = msg.getString();

	Position position;
	if (category == BUG_CATEGORY_MAP) {
		position = msg.getPosition();
	}

	addGameTask(&Game::playerReportBug, player->getID(), message, position, category);
}
```
with:
```
void ProtocolGame::parseBugReport(NetworkMessage& msg)
{
	std::string message = msg.getString();

	addGameTask(&Game::playerReportBug, player->getID(), message);
}
```
of course it will require changes in `Game::playerReportBug` and other functions, as there is no 'category' anymore.

**Comment by nekiro** [comment]
Fixed in https://github.com/nekiro/TFS-1.4-Downgrades/commit/80c09e479f10ed95958bccac1f9983177b488b9e
