### ISSUE TITLE
ManaFluids Animation

### ISSUE THREAD

**Issue by LampaPL** [nekiro/TFS-1.4-Downgrades#71]
**Protocol version**
8.00

**Describe the bug**
ManaFluids Animation

**Screenshots**
<a href="https://gyazo.com/c3e024df0498424f73534e0fee5d15a4"><img src="https://i.gyazo.com/c3e024df0498424f73534e0fee5d15a4.gif" alt="Image from Gyazo" width="1194"/></a>

**Comment by Emilianenko** [comment]
Change fromPosition to toPosition in this line: https://github.com/nekiro/TFS-1.4-Downgrades/blob/8.0/data/actions/scripts/other/fluids.lua#L49 and this line also https://github.com/nekiro/TFS-1.4-Downgrades/blob/8.0/data/actions/scripts/other/fluids.lua#L52.

**Comment by LampaPL** [comment]
Now is perfect!Thanks.
[![Image from Gyazo](https://i.gyazo.com/f34e3af90b466faff0c1d7c40baa6737.gif)](https://gyazo.com/f34e3af90b466faff0c1d7c40baa6737)
