### ISSUE TITLE
Damage received on mana shield

### ISSUE THREAD

**Issue by paola92** [nekiro/TFS-1.4-Downgrades#74]
**Protocol version**
8.00

**Describe the bug**
when someone use utamo vita then instead of damage received players is receiving random characters

**To Reproduce**
1. Use utamo vita and get some dmg

**Expected behavior**
display correct dmg received

**Screenshots**

**Additional context**

**Comment by paola92** [comment]
Fixed.
you have to change game.cpp and change:
_coloredText.text = manaDamage;_ to _coloredText.text = std::to_string(manaDamage);_

Thanks @gesior

**Comment by nekiro** [comment]
Care to submit pull request?
