### ISSUE TITLE
Saving items in depot and depotlocker

### ISSUE THREAD

**Issue by nefrenowiec** [nekiro/TFS-1.4-Downgrades#79]
**Protocol version**
8.60

**Describe the bug**
When player put items to depot or depotlocker and there is a save or player relog its ok but when he change places of these items i get error in console and character will not saved.

**To Reproduce**
1. Login to game
2. Put backpack in locker
3. Put 2 items to locker
4. Relog
5. change places of these 2 items
6. relog and error

**Expected behavior**

**Screenshots**

**Additional context**
I did this changes: https://github.com/nekiro/TFS-1.4-Downgrades/commit/e8614e2157a7120d7fb6fd6786e675ac6031097f
But it still not work

**Comment by nekiro** [comment]
Works properly here, cause I took the time to test it
![Y488VHXFv5](https://user-images.githubusercontent.com/14142246/143735940-b7ce9ec6-b582-4993-b9ff-e96a0b486ee1.gif)
.

**Comment by nefrenowiec** [comment]
@nekiro Look this: https://streamable.com/38vekh

**Comment by luanluciano93** [comment]
Error confirmed

**Comment by waqmaz93** [comment]
Confirmed on TFS 1.4 downgraded to version 7.72. If I put items to depo and logout I can not even login again. Console doesnt throw any errors.

**Comment by waqmaz93** [comment]
> Works properly here, cause I took the time to test it. ![Y488VHXFv5](https://user-images.githubusercontent.com/14142246/143735940-b7ce9ec6-b582-4993-b9ff-e96a0b486ee1.gif)
> 
> Don't know if I missed something or not, but next time exhaust your options before creating issue.

how did you created this gif? i want to reproduce the bug

**Comment by waqmaz93** [comment]
> Works properly here, cause I took the time to test it. ![Y488VHXFv5](https://user-images.githubusercontent.com/14142246/143735940-b7ce9ec6-b582-4993-b9ff-e96a0b486ee1.gif)
> 
> Don't know if I missed something or not, but next time exhaust your options before creating issue.

![aaaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/45514240/144452838-2d0e2748-f873-4ea4-8c29-bd59dbfa6b75.gif)


STEPS TO REPRODUCE THE BUG: 
Move items between depot and chest locker. I dont know if you need to move containers like backpacks and bags or not.

**Comment by dami1310** [comment]
Tested it for a bit and this is how I get it:
1. Put container with items inside into a locker/depot.
2. Relog
From now on character is not saving every time u put something into the dp.

**Comment by waqmaz93** [comment]
> Tested it for a bit and this is how I get it:
> 
> 1. Put container with items inside into a locker/depot.
> 2. Relog
>    From now on character is not saving every time u put something into the dp.

yeah im just testing it now for an hour already... im not sure why one time it works one time it doesnt maybe it has ti be a bag. still testing...

**Comment by waqmaz93** [comment]
the position must be changed in orther for the bug to work.
it hink the position when moved is not being deleted from data base thats why it says

Message: Duplicate entry '3-102' for key 'player_id_2

**Comment by waqmaz93** [comment]
This fatal bug allows to COPY ITEMS!!! Then console does not throw any errors. I have no idea why downgrading a proper working server caused all of these bugs... its like there were some crucifical changes in the code...
![vvvvvvvvvvvvvvvv](https://user-images.githubusercontent.com/45514240/144471941-0e195eb8-e95e-4271-af67-c71f0695d35f.gif)

**Comment by nekiro** [comment]
Fixed in https://github.com/nekiro/TFS-1.4-Downgrades/commit/fad6e9eb10cb5991b8df963a2ee6ffeffda93120
