### ISSUE TITLE
Fluid containers not working

### ISSUE THREAD

**Issue by EPuncker** [nekiro/TFS-1.4-Downgrades#80]
**Protocol version**
8.60

**Describe the bug**
All fluid containers are not working, they are not displaying if they are empty or not, and all of them have "infinite" water that you can splash in the ground

**To Reproduce**
1. /i 2014
2. Use it on the ground multiple times
3. See error

**Expected behavior**
Working lmao

**Comment by luanluciano93** [comment]
Cannot reproduce the error

**Comment by EPuncker** [comment]
![fayemi2](https://user-images.githubusercontent.com/4684880/143729148-0699315f-e2c7-4e49-8b91-6cef3b113fe3.gif)

**Comment by nekiro** [comment]
I came up with solution, looks like the flag isnt supplied by items.otb nor dat file of the client version.
You gonna have to add the flag to items.xml yourself like I did in this commit:
https://github.com/nekiro/TFS-1.4-Downgrades/commit/fe764b7bb6d4153fea5de601616e7bbe7223cedd
