### ISSUE TITLE
Stepping on parcels [BUG][7.72]

### ISSUE THREAD

**Issue by waqmaz93** [nekiro/TFS-1.4-Downgrades#82]
**Protocol version**
7.72

**Describe the bug**
Players can step up on 2 stacked parcels if followed conditions have had occured:

**To Reproduce**
1. Stand on 2 parcels and then add 2 more parcels under you so you have 4 parcels in total. 
2. Then take out 2 parcels so you have only 2 under you.
3.From now on you can step up on those 2 parcels

**Expected behavior**
Stepping up on more than 2 parcels should not be possible in the version of 7.72

**Screenshots**
Gifs have been added.

![parcel bug6](https://user-images.githubusercontent.com/45514240/144708498-95f79cda-4386-45f9-a85c-6b0f7dcde7e7.gif)
![dupa](https://user-images.githubusercontent.com/45514240/144713796-d8c0ec24-156e-4792-9be8-e7504bc54550.gif)

You can start here:
`ReturnValue Game::internalMoveCreature(Creature* creature, Direction direction, uint32_t flags /*= 0*/)
{
	creature->setLastPosition(creature->getPosition());
	const Position& currentPos = creature->getPosition();
	Position destPos = getNextPosition(direction, currentPos);
	Player* player = creature->getPlayer();

	bool diagonalMovement = (direction & DIRECTION_DIAGONAL_MASK) != 0;
	if (player && !diagonalMovement) 
	{
		if (creature->getTile()->hasHeight(1))
		{
			std::cout << "creature->getTile()->hasHeight 1\n";
		}
		if (creature->getTile()->hasHeight(2))
		{
			std::cout << "creature->getTile()->hasHeight 2\n";
		}
		if (creature->getTile()->hasHeight(3))
		{
			std::cout << "creature->getTile()->hasHeight 3\n";
		}
		if (creature->getTile()->hasHeight(4))
		{
			std::cout << "creature->getTile()->hasHeight 4\n";
		}

		Tile* tmpTile = map.getTile(destPos.x, destPos.y, destPos.z);

		if (tmpTile && tmpTile->hasHeight(1)) {
			std::cout << "tmpTile->hasHeight 1\n";
		}
		if (tmpTile && tmpTile->hasHeight(2)) {
			std::cout << "tmpTile->hasHeight 2\n";
		}
		if (tmpTile && tmpTile->hasHeight(3)) {
			std::cout << "tmpTile->hasHeight 3\n";
		}

		if (tmpTile && tmpTile->getGround()) {
			std::cout << "tile ground\n";
		}

		/*
		if (currentPos.z != 8 && creature->getTile()->hasHeight(3)) {
			Tile* tmpTile = map.getTile(currentPos.x, currentPos.y, currentPos.getZ() - 1);
			if (tmpTile == nullptr || (tmpTile->getGround() == nullptr && !tmpTile->hasFlag(TILESTATE_BLOCKSOLID))) {
				tmpTile = map.getTile(destPos.x, destPos.y, destPos.getZ() - 1);
				if (tmpTile && tmpTile->getGround() && !tmpTile->hasFlag(TILESTATE_BLOCKSOLID)) {
					flags |= FLAG_IGNOREBLOCKITEM | FLAG_IGNOREBLOCKCREATURE;

					if (!tmpTile->hasFlag(TILESTATE_FLOORCHANGE)) {
						player->setDirection(direction);
						destPos.z--;
					}
				}
			}
		}

		if (currentPos.z != 7 && currentPos.z == destPos.z) {
			Tile* tmpTile = map.getTile(destPos.x, destPos.y, destPos.z);
			if (tmpTile == nullptr || (tmpTile->getGround() == nullptr && !tmpTile->hasFlag(TILESTATE_BLOCKSOLID))) {
				tmpTile = map.getTile(destPos.x, destPos.y, destPos.z + 1);
				if (tmpTile && tmpTile->hasHeight(3)) {
					flags |= FLAG_IGNOREBLOCKITEM | FLAG_IGNOREBLOCKCREATURE;
					player->setDirection(direction);
					destPos.z++;
				}
			}
		}
		*/
	}

	Tile* toTile = map.getTile(destPos);
	if (!toTile) {
		return RETURNVALUE_NOTPOSSIBLE;
	}
	return internalMoveCreature(*creature, *toTile, flags);
}`

**Comment by nekiro** [comment]
Fixed in https://github.com/nekiro/TFS-1.4-Downgrades/commit/90a8e687cdebaca64372c7c07845c10b3706a4f4
