### ISSUE TITLE
Bug bless

### ISSUE THREAD

**Issue by luanluciano93** [nekiro/TFS-1.4-Downgrades#86]
**Protocol version**
8.60

**Describe the bug**
I'm using a talkaction to bless the player, but after a check I realized that only bless 1, 2 and 3 are being given, bless 4 and 5 are not working...

**To Reproduce**

```
function onSay(player, words, param)

	for i = 1, 5 do
		player:addBlessing(i)
		print("Add bless: ".. i ..".")
	end

	print("-----------------")

	for i = 1, 5 do
		if player:hasBlessing(i) then
			print("Ok bless: ".. i ..".")
		end
	end

	return false
end

```

**Comment by nekiro** [comment]
I dont think anything related to bless was even touched

**Comment by luanluciano93** [comment]
have you tested?

**Comment by nefrenowiec** [comment]
> have you tested?

If you want to give 5 bless you have to add value 32
player:addBlessing(32)
If you want to give 6 bless (twist of fate) you have to add 64
player:addBlessing(64)

**Comment by nekiro** [comment]
Bless 5 is twist of fate, which shouldn't be present in tibia 8.6 (as far as I remember)
Bless bitset indexes from 0 not 1, so you have to add 0, 1, 2, 3 bless to get all 4 blesses.
so change your loop to i = 0, 3 or add - 1 to i

**Comment by luanluciano93** [comment]
thank you
