### ISSUE TITLE
All distributions have wrong version name

### ISSUE THREAD

**Issue by floki21uu** [nekiro/TFS-1.4-Downgrades#87]
**Protocol version**
7.72/8.00/8.60

**Describe the bug**
In file named definitions.h it says that the version of the engine is 1.3 and not, as the author says on github 1.4:
> TFS-1.4-Downgrades

_Definitions.h:_
`static constexpr auto STATUS_SERVER_VERSION = "1.3 (Nekiro's 7.72 downgrade)";`

**Expected behavior**
Change the title of the server versions to "TFS-1.3-Downgrades"

**Comment by nekiro** [comment]
Actually it's 1.5, it was, because it wasnt synced with upstream
